### ISSUE TITLE
Support Feature Group Updates in aws_sagemaker_feature_group

### ISSUE THREAD

**Issue by lsamaha1-chwy** [SebastianUA/terraform-aws-sagemaker#10]
Amazon SageMaker supports adding features to existing Feature Group schema as of July 2022 (launch announced [here](https://aws.amazon.com/about-aws/whats-new/2022/07/amazon-sagemaker-feature-store-new-features-existing-feature-groups/)). Current Terraform plans handle additional columns as an operation that forces replacement. Please add support for updating existing feature groups with new features.

**Comment by SebastianUA** [comment]
Thanks @lsamaha1-chwy,
I will take a look at it and add a new logic.
