### ISSUE TITLE
Feature Group Output Name Attribute not exist

### ISSUE THREAD

**Issue by khaman-pet** [SebastianUA/terraform-aws-sagemaker#11]
I tested out the Feature Group module  (terraform plan) and received this error:
    
    │ Error: Unsupported attribute
    │ 
    │   on ../../sagemaker/outputs.tf line 186, in output "sagemaker_feature_group_name":
    │  186:   value       = element(concat(aws_sagemaker_feature_group.sagemaker_feature_group.*.name, [""]), 0)
    │ 
    │ This object does not have an attribute named "name".

The config that I use:

    module "sagemaker_feature_group" {
      source      = "../../sagemaker"
      name        = "TEST"
      environment = "stage"
    
      enable_sagemaker_feature_group = true
      sagemaker_feature_group_name = "feature-group-name"
      sagemaker_feature_group_record_identifier_feature_name = "record-identifier-feature-name"
      sagemaker_feature_group_event_time_feature_name = "event-time-feature-name"
      sagemaker_feature_group_role_arn = "arn:aws:anyarn:ap-southeast-1:123456789012:anytype:anyname"
      sagemaker_feature_group_description = "desc"
    
      sagemaker_feature_group_feature_definition = [{
        feature_name = "feature1"
        feature_type = "String" # Integral, Fractional, or String
      }]
    
      sagemaker_feature_group_offline_store_config = [{
        s3_storage_config = {
          s3_uri = "s3 bucket path"
          kms_key_id = "arn:aws:anyarn:ap-southeast-1:123456789012:anytype:anyname"
        }
        data_catalog_config = {
          catalog = "catalog"
          database = "db"
          table_name = "table-name"
        }
      }]
    
      sagemaker_feature_group_online_store_config = [{
        security_config = {
          kms_key_id = "arn:aws:anyarn:ap-southeast-1:123456789012:anytype:anyname"
        }
      }]
    }

If I commented out the feature group name output. It will work but we might need the name output in the future.

**Comment by SebastianUA** [comment]
Hi @khaman-pet 

Thank you for reporting! I commented on that output. It looks like a bug.
I merged the changes into the `master` brunch. Please let me know if it's working fine for you.
Thanks.

**Comment by khaman-pet** [comment]
Working without the 'name' output. 
Might be bugs in the HashiCorp documentation itself. As feature_group output 'id' exist, but not in the documentation.
