### ISSUE TITLE
missing platform_identifier in sagemaker_notebook_instance

### ISSUE THREAD

**Issue by antoine-tran** [SebastianUA/terraform-aws-sagemaker#3]
The "standard"  [notebook_instance resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_notebook_instance) supports the platform_identifier input variables, which allow either notebook-al1-v1, notebook-al2-v1, or notebook-al2-v2. 

This feature is missing in current version (1.2.6), which results in all notebook instance created by TF only has the old operating system notebook-al1-v1, where python3.8 is not supported.

**Comment by SebastianUA** [comment]
Hi @antoine-tran 

Thank you for your hands on. I added that variable to the file and pushed changes into master. You can start using it.
I'm going to make refactoring of the module soon and add more features. Then, I can create a new tag.

Let me know if you need something else from my side.
Thank you

**Comment by SebastianUA** [comment]
Done! You can use a new tag

**Comment by SebastianUA** [comment]
The tag is https://github.com/SebastianUA/terraform-aws-sagemaker/releases/tag/v2.0.0
