### ISSUE TITLE
Sagemaker_device error

### ISSUE THREAD

**Issue by aliwinter** [SebastianUA/terraform-aws-sagemaker#6]
## Description
When running terraform `sagemaker_device.tf` throws the following error, I'm guessing we want to change that to `var.enable_sagemaker_device`? After changing the variable from `var.enabele` to `var.enable_sagemaker_device` I get another error saying

### Error 1
```
│ Error: Reference to undeclared input variable
│ 
│   on .terraform/modules/service_sagemaker.sagemaker.sagemaker/sagemaker_device.tf line 7, in resource "aws_sagemaker_device" "sagemaker_device":
│    7:   device_fleet_name = var.sagemaker_device_fleet_name != "" ? var.sagemaker_device_fleet_name : (var.enabele_ ? aws_sagemaker_device_fleet.sagemaker_device_fleet[count.index].device_fleet_name : null)
│ 
│ An input variable with the name "enabele_" has not been declared. This variable can be declared with a variable "enabele_" {} block
```

### Error 2 
```
│ Error: Unsupported argument
│ 
│   on .terraform/modules/service_sagemaker.sagemaker.sagemaker/sagemaker_device.tf line 8, in resource "aws_sagemaker_device" "sagemaker_device":
│    8:   role_arn          = var.sagemaker_device_fleet_role_arn
│ 
│ An argument named "role_arn" is not expected here.
```

## Request
Change [these lines
](https://github.com/SebastianUA/terraform-aws-sagemaker/blob/e5f87f2a521338dfbdfb35c7da2c8dc9074fa3ed/sagemaker_device.tf#L7-L8) so that terraform init resolves.

**Comment by aliwinter** [comment]
Proposed Changes

**Comment by SebastianUA** [comment]
Hi @aliwinter 

Thank you very much! My mistake. 
I re-created the tag one more time: https://github.com/SebastianUA/terraform-aws-sagemaker/releases/tag/v2.0.0

**Comment by aliwinter** [comment]
@SebastianUA no worries, however I still get the error below, but if I remove  the line it works might be a bug? 

```
╷
│ Error: Unsupported argument
│ 
│   on .terraform/modules/service_sagemaker.sagemaker.sagemaker/sagemaker_device.tf line 8, in resource "aws_sagemaker_device" "sagemaker_device":
│    8:   role_arn          = var.sagemaker_device_fleet_role_arn
│ 
│ An argument named "role_arn" is not expected here.
╵
```

**Comment by SebastianUA** [comment]
@aliwinter, Try to update the AWS provider to `4.35.0`. The example:

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      // version = "~> 4.0"
      version = "4.35.0"
    }
  }
}
```

**Comment by SebastianUA** [comment]
@aliwinter 

BTW: you can make any changes and create a new PR. I will take a look at it and can merge and create a new tag for future contributing. If you want and have time for it.

**Comment by aliwinter** [comment]
Sure 👍🏽

**Comment by aliwinter** [comment]
@SebastianUA, I updated aws to version "4.35.0" and still get the same error.  If i remove the `role_arn` line, than the terraform init succeeds, any thoughts?

```
...
- Finding hashicorp/aws versions matching "4.35.0"...
...
- Installing hashicorp/aws v4.35.0...
- Installed hashicorp/aws v4.35.0 (signed by HashiCorp)
...
│ Error: Unsupported argument
│ 
│   on .terraform/modules/service_sagemaker.sagemaker.sagemaker/sagemaker_device.tf line 8, in resource "aws_sagemaker_device" "sagemaker_device":
│    8:   role_arn          = var.sagemaker_device_role_arn
│ 
│ An argument named "role_arn" is not expected here.
```

**Comment by SebastianUA** [comment]
Hey @aliwinter 

Agree with you + we can create a new bug in AWS provider.

**Comment by SebastianUA** [comment]
The bug has been created: https://github.com/hashicorp/terraform-provider-aws/issues/27434

**Comment by aliwinter** [comment]
thanks!!

**Comment by SebastianUA** [comment]
Hi @aliwinter 

Let's delete this parameter from the stack. I got the answer that's issue in documentation.

**Comment by aliwinter** [comment]
Awesome I'll open a PR
