### ISSUE TITLE
Support IceBerg File Format in aws_sagemaker_feature_group

### ISSUE THREAD

**Issue by lsamaha1-chwy** [SebastianUA/terraform-aws-sagemaker#9]
Requesting that Terraform add support for IceBerg format for SageMaker offline FeatureStore. SageMaker Feature Store added support for creating FeatureGroups with offline storage in iceberg format 12/2022 (announced [here](https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-sagemaker-feature-store-apache-iceberg-table-format/)). Examples of usage are [here](https://github.com/aws-samples/amazon-sagemaker-feature-store-end-to-end-workshop/blob/main/02-module-working-with-offline-store/m2_nb3_offline_iceberg_compaction.ipynb).

**Comment by SebastianUA** [comment]
Thanks @lsamaha1-chwy,
I will take a look at it and add a new logic.
